# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '不规则Collection' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Masonry'
  pod 'MJExtension'
  pod 'AbnormalityLabelView', :path=>'../'
  pod 'AbnormalityLabelView', :subspecs=>['Drawer'], :path=>'../'
  #  pod 'AbnormalityLabelView/Drawer', :path=>'../'

  # Pods for 不规则Collection

end
